brew "chezmoi"
brew "fzf"
brew "multimarkdown"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"

tap "d12frosted/emacs-plus"
cask "d12frosted/emacs-plus/emacs-plus-app"
cask "ghostty" unless File.exist?("/Applications/Ghostty.app")
cask "karabiner-elements" unless File.exist?("/Applications/Karabiner-Elements.app")

{{- if .company }}
brew "mise"
{{- end }}
