{{- $installPi := true -}}
{{- if hasKey . "installPi" -}}
{{-   $installPi = .installPi -}}
{{- end -}}
{{- $installOhMyPi := false -}}
{{- if hasKey . "installOhMyPi" -}}
{{-   $installOhMyPi = .installOhMyPi -}}
{{- end -}}
brew "chezmoi"
{{ if $installPi -}}
brew "fd"
{{ end -}}
{{ if or $installPi $installOhMyPi -}}
brew "ffmpeg"
{{ end -}}
brew "fzf"
brew "jq"
brew "mise"
brew "multimarkdown"
brew "reattach-to-user-namespace"
brew "the_silver_searcher"
brew "tmux"

tap "d12frosted/emacs-plus"
cask "d12frosted/emacs-plus/emacs-plus-app"
cask "ghostty" unless File.exist?("/Applications/Ghostty.app")
cask "karabiner-elements" unless File.exist?("/Applications/Karabiner-Elements.app")
